[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://grubgo-rosy.vercel.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400" 